### ISSUE TITLE
Getting an exception

### ISSUE THREAD

**Issue by cdietrich** [itemis/generator-xtext#11]
```
Welcome to the Xtext Yeoman generator.
? Project name: org.xtext.example.mydsl
? Language name: org.xtext.example.mydsl.MyDsl
? File extension: mydsl
? Select the facets you would like to use: testing, ide, web
? Select your web framework: CodeMirror

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: When copying multiple files, provide a directory as destination
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-xtext/node_modules/mem-fs-editor/lib/actions/copy.js:34:5)
    at _setupGradleBuild (/usr/local/lib/node_modules/generator-xtext/generators/app/index.js:115:13)
    at writing (/usr/local/lib/node_modules/generator-xtext/generators/app/index.js:100:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-xtext/node_modules/yeoman-generator/lib/index.js:417:23)
    at /usr/local/lib/node_modules/generator-xtext/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-xtext/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-xtext/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by cdietrich** [comment]
https://github.com/SBoudrias/mem-fs-editor/issues/70

**Comment by cdietrich** [comment]
@franzbecker the templates folder has no .gitignore
